export const SET_FILTER_NAME = 'SET_FILTER_NAME'

export const SET_SORT_FIELD = 'SET_SORT_FIELD'

export const SET_SORT_ORDER = 'SET_SORT_ORDER'

export const SET_DEFAULT = 'SET_DEFAULT'

export const GET_RUSHING_STATS_REQUEST = 'GET_RUSHING_STATS_REQUEST'

export const GET_RUSHING_STATS_SUCCESS = 'GET_RUSHING_STATS_SUCCESS'

export const GET_RUSHING_STATS_ERROR = 'GET_RUSHING_STATS_ERROR'

export const DOWNLOAD_CSV_REQUEST = 'DOWNLOAD_CSV_REQUEST'

export const DOWNLOAD_CSV_SUCCESS = 'DOWNLOAD_CSV_SUCCESS'

export const DOWNLOAD_CSV_ERROR = 'DOWNLOAD_CSV_ERROR'